FROM archlinux:latest

RUN pacman -Sy --noconfirm \
    base-devel \
    rust \
    cargo \
    chezmoi \
    && pacman -Scc --noconfirm

WORKDIR /work

ENV CARGO_TARGET_DIR=/tmp/cargo-target

CMD ["bash", "-lc", "bash -n run_once_install-packages.sh.tmpl && cd installer && cargo build --release && /tmp/cargo-target/release/dotsetup install"]
